controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
